# Loan Repayment

**Amortizing a loan (debt, mortgage)** Part of the repayment is used to repay the **interest due** called **interest payments**. The excess of the interest due is used repay the original loan (the principal), called **principal repayments**. The remaining amount of the loan is called the **outstanding loan balance**. 

**Amortization schedule** A table which shows the interrelationships between the balance, principal payments, and interest payments over the life of a loan.

**Sinking fund approach** Repay the interest due and the principal separately (the loan amount does not change over the life of the loan): the interest due is repaid regularly during the loan period; the principal is repaid at the end of the loan period by a sinking fund. A fund designed to accumulate a specified amount of money in a specified time by making regular deposits is called a **sinking fund**.

**Equal principal repayments** Each repayments (decreasing repayments) involves (1) the level amounts of principal and (2) the interest on the outstanding balance. 


