# Homework {-}

## Week 2 {-}

## Week 1 {-}

### Problem 1 {-}

John invests $X$ in a fund growing in accordance with the accumulation function implied by the *amount function*
$$A(t)=4t^2+8t+4.$$
Edna invests $X$ in another fund growing in accordance with the accumulation function implied by the amount function $$A(t)=4t^2+2.$$
When does Edna's investment *exceed* John’s?

### Problem 2 {-}

What deposit made today will provide for a payment of $\$1000$ in 1 year and $\$2000$ in 3 years, if the effective rate of interest is $7.5\%$?

### Problem 3 {-}

Company $X$ received the approval to start no more than two projects in the current calendar year.
Three different projects were recommended, each of which requires an investment of 800 to be made at the beginning of the year.

The cash flows for each of the three projects are shown in Table \@ref(tab:week1):
```{r week1,echo=FALSE}
table1<-data.frame(matrix(c(1,500,500,500, 
         2,500,300,250, 
         3,-175,-175,-175,
         4,100,150,200,
         5,0,200,200),nrow=5,byrow = T))
names(table1)<-c("End of year", "Project A", "Project B", "Project C")
knitr::kable(table1,caption = "The cash flows of the three projects.")
```

The company uses an annual effective interest rate of $10\%$ to discount its cash flows. 

Determine which combination of projects the company should select.







